from fpdf import FPDF
from datetime import datetime

class ISROReport(FPDF):
    def header(self):
        self.set_fill_color(10, 25, 47) 
        self.rect(0, 0, 210, 25, 'F')
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(0, 229, 255) 
        self.set_y(8)
        self.cell(0, 10, 'ISRO REGISTRATION METRICS REPORT', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Registration Engine', 0, 0, 'C')

def generate_mission_report(metrics: dict, src_shape: tuple, ref_shape: tuple, tps_requested: bool, asift_enabled: bool, scale_ratio: str, diagnostics: dict, actual_tps_used: bool) -> bytes:
    pdf = ISROReport()
    pdf.add_page()
    
    pdf.set_font("Helvetica", size=10)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, f"Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}", 0, 1, 'R')
    pdf.ln(5)
    
    pdf.set_font("Helvetica", 'B', 14)
    pdf.set_text_color(0, 114, 255)
    pdf.cell(0, 10, "1. REGISTRATION CONFIGURATION", 0, 1)
    
    pdf.set_font("Courier", size=11)
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_fill_color(245, 245, 245)
    pdf.cell(0, 8, f" Source Image Resolution       : {src_shape[1]} x {src_shape[0]} px", border=1, ln=1, fill=True)
    pdf.cell(0, 8, f" Reference Map Resolution      : {ref_shape[1]} x {ref_shape[0]} px", border=1, ln=1, fill=True)
    pdf.cell(0, 8, f" Detected Multi-Scale Ratio    : {scale_ratio}", border=1, ln=1, fill=True)
    pdf.cell(0, 8, f" Affine-SIFT Application       : {'[ ACTIVE - Viewpoint Invariant ]' if asift_enabled else '[ INACTIVE ]'}", border=1, ln=1, fill=True)
    
    if tps_requested and actual_tps_used:
        tps_status = "[ ACTIVE - Non-Rigid Warp ]"
    elif tps_requested and not actual_tps_used:
        tps_status = "[ FALLBACK - Homography used due to unsafe constraints ]"
    else:
        tps_status = "[ INACTIVE ]"
    
    pdf.cell(0, 8, f" Thin Plate Spline Application : {tps_status}", border=1, ln=1, fill=True)
    
    pdf.ln(10)
    
    pdf.set_font("Helvetica", 'B', 14)
    pdf.set_text_color(0, 114, 255)
    pdf.cell(0, 10, "2. ALIGNMENT QUALITY METRICS", 0, 1)
    
    pdf.set_font("Courier", 'B', 11)
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_fill_color(230, 240, 255)
    pdf.cell(95, 10, " METRIC", border=1, fill=True)
    pdf.cell(95, 10, " RESULT", border=1, ln=1, fill=True)
    
    pdf.set_font("Courier", size=11)
    pdf.cell(95, 10, " RMSE (Geometric Error)", border=1)
    pdf.cell(95, 10, f" {metrics.get('RMSE', 0.0):.4f} Pixels", border=1, ln=1)
    
    pdf.cell(95, 10, " Verified Topologic Inliers", border=1)
    pdf.cell(95, 10, f" {metrics.get('Inliers', 0)} Match Points", border=1, ln=1)
    
    pdf.cell(95, 10, " Inlier Ratio", border=1)
    pdf.cell(95, 10, f" {(metrics.get('Inlier_Ratio', 0.0)*100):.2f} %", border=1, ln=1)
    
    pdf.cell(95, 10, " Mutual Information", border=1)
    pdf.cell(95, 10, f" {metrics.get('Mutual_Info', 0.0):.4f} bits", border=1, ln=1)
    
    pdf.cell(95, 10, " Structural Similarity (SSIM)", border=1)
    pdf.cell(95, 10, f" {metrics.get('SSIM', 0.0):.2f} %", border=1, ln=1)
    
    pdf.ln(10)
    pdf.set_font("Helvetica", 'B', 14)
    pdf.set_text_color(0, 114, 255)
    pdf.cell(0, 10, "3. DIAGNOSTICS & VALIDATION", 0, 1)
    
    pdf.set_font("Courier", 'B', 11)
    pdf.set_text_color(0, 0, 0)
    
    pdf.set_fill_color(255, 245, 230)
    pdf.cell(95, 10, " VALIDATION PARAMETER", border=1, fill=True)
    pdf.cell(95, 10, " MEASUREMENT", border=1, ln=1, fill=True)
    
    pdf.set_font("Courier", size=11)
    
    val_median = metrics.get('validation_median_error', 0.0)
    pdf.cell(95, 10, " Validation Median Error", border=1)
    pdf.cell(95, 10, f" {val_median:.4f} Pixels", border=1, ln=1)
    
    val_p95 = metrics.get('validation_p95_error', 0.0)
    pdf.cell(95, 10, " 95th Percentile Error", border=1)
    pdf.cell(95, 10, f" {val_p95:.4f} Pixels", border=1, ln=1)
    
    coverage = metrics.get('spatial_coverage', 0.0)
    pdf.cell(95, 10, " Spatial Coverage", border=1)
    pdf.cell(95, 10, f" {coverage:.2f} %", border=1, ln=1)

    status = metrics.get('quality_status', 'Unknown')
    pdf.cell(95, 10, " Assessed Quality Status", border=1)
    pdf.cell(95, 10, f" {status}", border=1, ln=1)

    pts_src = metrics.get('subpixel_source_points', 0)
    pts_ref = metrics.get('subpixel_reference_points', 0)
    pdf.cell(95, 10, " Sub-pixel Refined Points", border=1)
    pdf.cell(95, 10, f" {pts_src} Src / {pts_ref} Ref", border=1, ln=1)
    
    runtime = metrics.get('runtime', 0.0)
    pdf.cell(95, 10, " Total Processing Time", border=1)
    pdf.cell(95, 10, f" {runtime:.2f} seconds", border=1, ln=1)

    pdf.ln(10)
    
    pdf.set_font("Helvetica", 'B', 12)
    pdf.set_text_color(0, 114, 255)
    pdf.cell(0, 8, "EXECUTIVE SUMMARY:", 0, 1)
    
    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(50, 50, 50)
    summary_text = (
        "The software successfully completed the geometric alignment and registration sequence. "
        "Illumination variance was addressed using Multi-Scale Retinex preprocessing. "
        "Dynamic scale pyramids were utilized to map varying spatial resolutions. "
        "Matched points were filtered using spatial quadtree bucketing, mapped, and mathematically registered. "
        "Correspondences were mathematically refined to sub-pixel precision using corner detection techniques."
    )
    pdf.multi_cell(0, 6, summary_text)
    
    return bytes(pdf.output())